apiVersion: v1
kind: Service
metadata:
  name: staging-guestbook-service
  labels:
    app: guestbook
    tier: frontend
  namespace: staging
spec:
  ports:
  - port: 80
  selector:
    app: guestbook
    tier: frontend
